; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_d32]
platform = espressif32@6.4.0
board = lolin_d32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder, time
board_build.partitions = huge_app.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=1
	-DBOOKIE_LOG_DEBUG=0
lib_deps = 
	adafruit/Adafruit PN532@^1.3.2
	earlephilhower/ESP8266Audio@^1.9.9
	miguelbalboa/MFRC522@^1.4.11
	adafruit/Adafruit NeoPixel@^1.12.3
	adafruit/Adafruit GFX Library@^1.11.11

[env:lolin_d32-debug]
extends = env:lolin_d32
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DBOOKIE_LOG_DEBUG=1
